<h2>MerchanCS - Administration</h2>
	
    

    
<!--<div class="input-group addItem">
<input class="form-control" type="text" placeholder="+ Add New Item">
<span class="input-group-btn">
<button class="btn btn-default" type="button">Submit</button>
</span>
</div>-->
	

</nav>
</header>

<section id="editAside">
	
<nav>

<form name="addItemForm" action="" onsubmit="return validateForm()" method="">
<input type="text" name="newItemText" placeholder="+ Add New Item">
<input type="submit" name="newItemButton"  value="Submit">
</form>    
    <div class="CSSTableGenerator" >
                <table >
                    <tr>
                        <td>
                            <h2>Edit Current Merchandise</h2>
                        </td>
                        
                    </tr>
                    <tr>
                        <td >
                            
                            <li><a class="text" href="#">Edit/Delete</a></li>
                            <h2> Floppy disks </h2>
                            <p> Price: $X.XX </p>
                        </td>
                        
                    </tr>
                    <tr>
                        <td >
                            
                            <li><a class="text" href="#">Edit/Delete</a></li>
                            <h2> Bananas </h2>
                            <p> Price: $X.XX </p>
                        </td>
                        
                    </tr>
                    <tr>
                        <td >
                            
                            <li><a class="text" href="#">Edit/Delete</a></li>
                            <h2> Wooden Brick </h2>
                            <p> Price: $X.XX </p>
                        </td>
                        
                    </tr>
                    <tr>
                        <td >
                            
                            <li><a class="text" href="#">Edit/Delete</a></li>
                            <h2> Sunscreen </h2>
                            <p> Price: $X.XX </p>
                        </td>
                        
                    </tr>
                </table>
            </div>