<?php
	$this->auth();
	
	// if(isset($_session['authenticated']) && $_session['authenticated'] == true) {
		// header("location: index.php");
		// exit;
	// }
?>

<body class="electric">
<header id="main-header">
    <a id="logo" class="navbar-brand" href="index.php"><img alt="MerchanCS Logo" class="logo" src="images/logo.jpg"></a>
</header>
<form  name="loginForm" action="index.php?page=login" onSubmit="return validateForm()" method="post">
<h2>Login: </h2>


<!--
<ul class="nav navbar-nav navbar-right">
<li><a class="home" href="#"><i class="fa fa-home text-inherit"></i> Home</a></li>
<li><a class="search" href="#"><i class="fa fa-search text-inherit"></i> Search</a></li>
<li><a class="browse" href="#"><i class="fa fa-bars text-inherit"></i> Browse</a></li>

<li class="dropdown themes">
<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="background-inherit demo-disk"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a data-class="apple" href="#"><span class="apple-instance demo-disk"></span> Apple</a></li>
<li><a class="active" data-class="electric" href="#"><span class="electric-instance demo-disk"></span> Electric</a></li>
<li><a data-class="lime" href="#"><span class="lime-instance demo-disk"></span> Lime</a></li>
<li><a data-class="oak" href="#"><span class="oak-instance demo-disk"></span> Oak</a></li>
</ul>
</li>
</ul>
-->
	
<div class="input-group username">
<input name="username" autocomplete="off" class="form-control" type="text" placeholder="Username">
</div>
    
<div class="input-group password">
<input name="password" class="form-control" type="password" placeholder="Password">
<span class="input-group-btn"></span>  
</div>
    
 <input type="submit" name="loginButton" value="Login">   

<!--<button id = "submitButton" class="btn btn-default" type="button" onclick="window.location = 'login2.html';">Submit</button>-->
    
</form>