<?php
	$this->fetch();
?>
<section class="banner">
<img alt="floppies" src="images/<?php echo $this->item->image; ?>"/>
	
<footer>
<button class="btn btn-primary" id="add-to-cart">$<?php echo $this->item->price; ?> - Buy with Boatright Wallet&reg;</button>
</footer>
</section>
<section class="description">
<h2><?php echo $this->item->name; ?></h2>
<p><?php echo $this->item->description; ?></p>
</section>