<?php
	$this->fetch();
?>

<div id="page-content-wrapper">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h2>Search Results</h2>
				
				<ul class="search">
                <?php
					foreach($this->items as $item) {
						echo "<li>
						<a href=\"index.php?page=product&id=" . $item->ID . "\">
							<img alt=\"Floppy\" src=\"images/" . $item->image . "\"/>
							<h3>" . $item->name . "</h3>
							<p>$" . $item->price . "</p>
						</a>
					</li>";	
					}
				?>
				</ul>
			</div>
		</div>
	</div>
</div>